services:
  timocloud:
    container_name: timocloud-main
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS_CORE=-Xmx1g -Xms256m -XX:+UseG1GC -XX:+UseStringDeduplication
      - JAVA_OPTS_BASE=-Xmx512m -Xms128m -XX:+UseG1GC -XX:+UseStringDeduplication
      - JAVA_OPTS_CORD=-Xmx256m -Xms64m -XX:+UseG1GC -XX:+UseStringDeduplication
    ports:
      - "7777:7777"
      - "7778:7778"
      - "7779:7779"
      - "7780:7780"
      - "25565:25565"
    volumes:
      - timocloud-data:/home/timocloud/storage
      - timocloud-logs:/home/timocloud/logs
      - timocloud-templates:/home/timocloud/templates
      - timocloud-temporary:/home/timocloud/temporary
      - timocloud-core-config:/home/timocloud/core
      - timocloud-base-config:/home/timocloud/base
      - timocloud-cord-config:/home/timocloud/cord
    networks:
      - timocloud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep -f 'TimoCloud.jar' > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  timocloud-data:
    driver: local
  timocloud-logs:
    driver: local
  timocloud-templates:
    driver: local
  timocloud-temporary:
    driver: local
  timocloud-core-config:
    driver: local
  timocloud-base-config:
    driver: local
  timocloud-cord-config:
    driver: local

networks:
  timocloud-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
